/**:
  ros__parameters:
    directory1: /your_work_space/src/long_term_mapping/Campus1
    directory2: /your_work_space/src/long_term_mapping/Campus2
    output_directory: "mergeMap"
    posegraph:
      dop_thres: 1.1
      fov_d: -15.0
      fov_u: 15.0
      max_distance: 100
      min_distance: 1
      num_angle: 120
      num_candidates_from_tree: 20
      num_exclude_recent: 0
      num_height: 16
      num_range: 100
      r_solid_thres: 0.95
      voxel_size: 0.4
    preprocess:
      blind: 1.0
